### ISSUE TITLE
Seeing DEBUG level logs after adding logcaptor dependency

### ISSUE THREAD

**Issue by joc-a** [Hakky54/log-captor#47] opened 2023-08-29 12:16 UTC
**Describe the bug**
I started seeing DEBUG level logging after adding the logcaptor dependency.
`logger.isDebugEnabled` is now returning true.

**To Reproduce**
I'm using slf4j and this is the log4j2.xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="info">
    <Appenders>
        <Console name="CONSOLE" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{ABSOLUTE} %5p %t %c{1}:%M:%L - %m%n"/>
        </Console>
        <Async name="ASYNC" includeLocation="true">
            <AppenderRef ref="CONSOLE"/>
        </Async>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="ASYNC"/>
        </Root>
        <Logger name="LoggerName" level="info" additivity="false">
            <AppenderRef ref="ASYNC"/>
        </Logger>
    </Loggers>
</Configuration>
```

**Expected behavior**
How can I keep the same level of logging as before adding the dependency?

**Screenshots**

**Environmental Data:**
 - Java Version
 - Maven Version
- OS (Windows/Linux/MacOS)

**Additional context**

**Comment by Hakky54** [comment] 2023-08-30 20:53
Do you mean that you are seeing these debug logs within your build output when running the tests?

**Comment by Hakky54** [comment] 2023-09-06 10:38
We have resolved this issue together with the pull request for the exposed library here: https://github.com/JetBrains/Exposed/pull/1852

The issue is not a bug but related to the underlying engine of LogCaptor which is outside of the control of LogCaptor itself. It is using Logback as SLF4J binding/implementation and Logback is using his own kind of logging configuration. So the log4j2.xml logger configuration is being ignored during the test resulting in showing also debug logs while previously disabled.

Solution is to add a logback-test.xml file in the test resources which is similar to the log4j2.xml configuration file. The file content of the logback-test.xml file is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%date{HH:mm:ss.SSS} %level %thread %logger{0}:%method:%line - %message %n</pattern>
        </encoder>
    </appender>
    <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="CONSOLE"/>
        <includeCallerData>true</includeCallerData>
    </appender>

    <root level="INFO">
        <appender-ref ref="ASYNC" />
    </root>
    <logger name="Exposed" level="INFO" additivity="false">
        <appender-ref ref="ASYNC"/>
    </logger>
</configuration>

<!-- 19:57:29.845 DEBUG Test worker Exposed - DROP TABLE jointable -->
```

Please note that the above configuration is written for a specific project, if copied you need to adjust the logger name ad maybe ad additional loggers to further configure your logs. I am closing this issue, thank you @joc-a I think this is valuable for anyone who wil encounter the same issue.

**Closed by Hakky54** 2023-09-06 10:38 UTC
